// Knowledge/react-app/src/components/Searchbar.js
import React, { Component } from 'react';
import Grid from './Grid';
import '../css/searchbar.scss';
import '../css/grid.scss';

const URL_TO_RETRIEVE_DATA = 'https://api.myjson.com/bins/uptto';

class Searchbar extends Component {
  constructor(props) {
    super(props);

    this.state = {
      data: {}
    };
  }

  componentDidMount() {
    fetch(URL_TO_RETRIEVE_DATA)
      .then(response => response.json())
      .then(dataJson => this.setState({ data: dataJson }));
  }

  render() {
    if(this.state.data.companies){
      return (
        <div>
          <div className="searchbar">
            <input onChange = {this.inputText} type="text" className="searchbar__textfield" placeholder="Buscar por Ubicación"/>
          </div> 
          <div className="agent-section">
            {this.state.data.companies.map((agent, i) => <Grid key = {i} data = {agent} />)}
          </div>
        </div>
        );
    }
    return (
      <div>
        <div className="searchbar">
          <input onChange = {this.inputText} type="text" className="searchbar__textfield" placeholder="Buscar por Ubicación"/>
        </div>
        <div className="agent-section"></div>
      </div>
      );
    }
  }
  

export default Searchbar;

// I do magic/angular-proj/src/app/searchbar/searchbar.component.ts
import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'app-searchbar',
  templateUrl: './searchbar.component.html',
  styleUrls: ['./searchbar.component.scss']
})
export class SearchbarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="searchbar">
    <input type="text" class="searchbar__textfield" placeholder="Buscar por Ubicación" name="Location" onkeypress="validateEnter(event)">
    <input type="image" src="../../assets/search.png" class="searchbar__search-button" onclick="getAgents('https://api.myjson.com/bins/uptto')">    
</div>
