// Knowledge/react-app/src/components/Grid.js
import React, { Component } from 'react';
import '../css/grid.scss';

class Grid extends Component {
  render() {
    if(this.props.data.isCertified){
      return (
        <div className="agent">
          <p className="agent__name">{this.props.data.name}</p>
          <div alt="ribbon" className="agent__ribbon"/>
          <div className="agent__separator"></div>
          <img className="agent__photo" src="{this.props.data.image}"/>
          <div className="agent__description">{this.props.data.description}</div>
          <div className="agent__price">Desde: ${this.props.data.rate} / {this.props.data.hours} horas</div>
          <div className="agent__button">
            <div className="agent__button-text">Contratar</div>
          </div>
        </div>
      );
    }
    return (
      <div className="agent">
        <p className="agent__name">{this.props.data.name}</p>
        <div className="agent__separator"></div>
        <img className="agent__photo" src="{this.props.data.image}"/>
        <div className="agent__description">{this.props.data.description}</div>
        <div className="agent__price">Desde: ${this.props.data.rate} / {this.props.data.hours} horas</div>
        <div className="agent__button">
          <div className="agent__button-text">Contratar</div>
        </div>
      </div>
    );
    
  }
}

export default Grid;

// I do magic/angular-proj/src/app/grid/grid.component.ts
import { Component, OnInit, HostBinding} from '@angular/core';
import { DataService } from '../data.service';

@Component({
  selector: 'app-grid',
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.scss']
})
export class GridComponent implements OnInit {

  agents: object = {companies:[]};


  constructor(private data: DataService) { }

  ngOnInit() {
    this.data.getAgents().subscribe(data => this.agents = data);
    this.data.currentData.subscribe(
      data => this.agents.companies = data
    );
  }



}

<div class="agent-section" *ngIf="agents.companies">
  <div *ngFor="let agent of agents.companies" class="agent" >
    <p class="agent__name">{{agent.name}}</p>
    <img *ngIf="agent.isCertified" src="../../assets/certified.png" alt="ribbon" class="agent__ribbon">
    <div class="agent__separator"></div>
    <img class="agent__photo" src="{{agent.image}}">
    <div class="agent__description">{{agent.description}}</div>
    <div class="agent__price">Desde: ${{agent.rate}} / {{agent.hours}} horas</div>
    <div class="agent__button">
      <div class="agent__button-text">Contratar</div>
    </div>
  </div>
</div>
